#!/bin/sh

# This file was automatically generated by the nomad-pi `create-config`
# script.

# Updated: @@time@@

if [ -f "/opt/local/bin/nomad" ]; then
    echo "Found existing Nomad binary in /opt/local/bin; exiting"
    exit 0
fi

set -ex

apt install -y avahi-daemon docker.io unzip

mkdir -p /opt/local/bin
mkdir -p /etc/consul.d
mkdir -p /etc/nomad.d

mkdir -p /opt/consul
chown consul /opt/consul

mkdir -p /opt/nomad
chown nomad /opt/nomad

cd /tmp

curl -o ./consul-bin.zip \
    @@consul_url@@

unzip ./consul-bin.zip
install ./consul /opt/local/bin

curl -o ./nomad-bin.zip \
    @@nomad_url@@

unzip ./nomad-bin.zip
install ./nomad /opt/local/bin

rm -f ./consul ./consul-bin.zip ./nomad ./nomad-bin.zip

systemctl enable --now consul
systemctl enable --now nomad

echo "export PATH=$PATH:/opt/local/bin" >> /home/nomad/.bashrc
echo "export TERM=xterm-color" >> /home/nomad/.bashrc
